name: insani_frontend
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^8.0.0
  cupertino_icons: ^1.0.8
  http: ^1.2.1
  shared_preferences: ^2.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 # Versi disesuaikan dengan SDK 3.10
  

flutter:
  uses-material-design: true

  assets:
    - assets/logorsi.png
    - assets/rsi.jpeg
    